### ISSUE TITLE
Explore Batch Create/Update

### ISSUE THREAD

**Issue by StanBarrows** [codebar-ag/laravel-docuware#123]
- [ ] Explore Batch Create/Update

**Comment by RhysLees** [comment]
@StanBarrows <img width="1245" alt="image" src="https://github.com/codebar-ag/laravel-docuware/assets/43909932/f8781d60-1afc-491f-9b37-d18f33b605f4">

BATCH Create will require an index.xml file to create the request

**Comment by RhysLees** [comment]
@StanBarrows <img width="923" alt="image" src="https://github.com/codebar-ag/laravel-docuware/assets/43909932/6cdd541e-4370-4854-b55a-c5a981689eb6">

BATCH Update fields seems to be a simple request where you have to specify a condition of the field and its possible current  values. then also its desired value
