### ISSUE TITLE
Release v1

### ISSUE THREAD

**Issue by StanBarrows** [codebar-ag/laravel-docuware#13]
### Discussed in https://github.com/codebar-ag/laravel-docuware/discussions/12

<div type='discussions-op-text'>

<sup>Originally posted by **StanBarrows** July  8, 2021</sup>
- [ ] Release v1</div>

**Comment by SuddenlyRust** [comment]
Tagged [v1.0.0](https://github.com/codebar-ag/laravel-docuware/releases/tag/1.0.0)
