### ISSUE TITLE
[Bug]:  Paginator Total show 1 instead of 0

### ISSUE THREAD

**Issue by StanBarrows** [codebar-ag/laravel-docuware#146]
### What happened?
Total is one even that Documents is empty!

![CleanShot 2024-06-19 at 01 55 11@2x](https://github.com/codebar-ag/laravel-docuware/assets/10268813/7af8dd7e-43d6-4e5d-a8d9-45ebc0367c4f)

### Package Version

-

### PHP Version

8.3

### Laravel Version

10.*

**Comment by RhysLees** [comment]
This is because you are on page 2, the total shows the total records in docuware, not on the page. this is the value that docuware gives in the api
