### ISSUE TITLE
items => documents

### ISSUE THREAD

**Issue by StanBarrows** [codebar-ag/laravel-docuware#7]
![CleanShot 2021-04-29 at 08 25 07](https://user-images.githubusercontent.com/10268813/116509941-6e266b00-a8c4-11eb-9343-191df7ccbdf2.png)

**Comment by SuddenlyRust** [comment]
Fixed with https://github.com/codebar-ag/laravel-docuware/commit/77a5725847f874dc961b843630b5dbc22665bdd0
